{
  imports = [
    ./catppuccin.nix
    ./fastfetch.nix
    ./git.nix
    ./kitty.nix
    ./neovim.nix
    ./spicetify.nix
    ./starship.nix
    ./yazi.nix
    ./zsh.nix
    ./wms/hyprland.nix
    ./wms/hypridle.nix
    ./wms/hyprlock.nix
    ./wms/dunst/dunst.nix
    ./wms/rofi/rofi.nix
    ./wms/eww/eww.nix
    ./wms/swappy.nix
  ];
}
